NTFY_AUTH_USERS='cat:{{ op://Personal/ntfy-amalthea/user_password_hash }}:user,uptime-kuma:{{ op://Personal/ntfy-amalthea/uptime_kuma_password_hash }}:user,pheme-watch:{{ op://Personal/ntfy-amalthea/pheme_watch_password_hash }}:user'
NTFY_AUTH_ACCESS='cat:*:rw,uptime-kuma:alerts:wo,pheme-watch:alerts:wo'
NTFY_AUTH_TOKENS='cat:{{ op://Personal/ntfy-amalthea/user_token }}:Personal,uptime-kuma:{{ op://Personal/ntfy-amalthea/uptime_kuma_token }}:Uptime Kuma,pheme-watch:{{ op://Personal/ntfy-amalthea/pheme_watch_token }}:Pheme watcher'
NTFY_WEB_PUSH_PUBLIC_KEY='{{ op://Personal/ntfy-amalthea/web_push_public_key }}'
NTFY_WEB_PUSH_PRIVATE_KEY='{{ op://Personal/ntfy-amalthea/web_push_private_key }}'
