# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
      kernelModules = [ ];

      luks.devices."luks-e12696b1-da5d-4aa3-8cda-ac2f90745068".device = "/dev/disk/by-uuid/e12696b1-da5d-4aa3-8cda-ac2f90745068";

      network = {
        enable = true;

        ssh = {
          enable = true;
          port = 2222; # separate from normal sshd

          authorizedKeys = [
            "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFP05x9Bg50efrFPX0NXfV45RwcsYmgpKUKTnR2Ee7LA cat"
          ];

          hostKeys = [
            "/etc/secrets/initrd/ssh_host_ed25519_key"
          ];
        };

        flushBeforeStage2 = true;

        postCommands = ''
      cat > /root/.profile <<'EOF'
      echo
      echo "To unlock root, run:"
      echo "  cryptsetup luksOpen /dev/disk/by-uuid/e12696b1-da5d-4aa3-8cda-ac2f90745068 cryptroot"
      echo
      exec /bin/sh
      EOF
      '';
      };
    };
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "/dev/mapper/luks-e12696b1-da5d-4aa3-8cda-ac2f90745068";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/90C2-339C";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
